language: elixir
elixir:
  - 1.4.1
otp_release:
  - 18.2.1
addons:
services:
before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate
script:
  - mix test --exclude integration
